name: mrz_scanner
description: A package that allows you to Scan any kind of documents that have any mrz format
version: 0.0.1+3
homepage: https://github.com/F-BONAPARTA/mrz_scanner

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  mrz_parser: ^2.0.0
  google_mlkit_text_recognition: ^0.9.0
  google_mlkit_commons: ^0.5.0
  camerawesome: ^2.0.0-dev.1
  google_mlkit_barcode_scanning: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
